# Generated by Django 3.2.13 on 2022-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('date', models.DateField(verbose_name='날짜')),
                ('status', models.CharField(choices=[('NO', '미지정'), ('AT', '출석'), ('AB', '결석'), ('PT', '일부참여')], default='NO', max_length=2, verbose_name='출석 여부')),
                ('description', models.TextField(blank=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '출석부',
                'verbose_name_plural': '출석부 목록',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('is_answered', models.BooleanField(default=False, help_text='체크가 되어 있으면, 답변이 완료된 항목입니다', null=True, verbose_name='답변 여부')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='qs/image/', verbose_name=' 스크린샷')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문 목록',
            },
        ),
    ]
