# Generated by Django 3.2.13 on 2022-10-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmingup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='갱신일'),
        ),
    ]
