# Generated by Django 3.2.13 on 2022-10-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('age', models.PositiveSmallIntegerField(verbose_name='나이')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('description', models.TextField(blank=True, verbose_name='소개')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='갱신일')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필 목록',
            },
        ),
    ]
